### ISSUE TITLE
Documentation for data in/export

### ISSUE THREAD

**Issue by mlukaszczyk** [GraphCMS/Roadmap#10]
To help our users to better understand how data can be imported or exported from GraphCMS, we will release some guides and examples that will show how this can be done.

**Comment by mlukaszczyk** [comment]
Update: 
We have built in the export feature. See https://graphcms.com/docs/guides/Export_schema_and_content/

**Comment by tomByrer** [comment]
Nice!

One small docs suggestion: add extra vertical space between the example schema.txt output & the paragraph explaining the data dump.  Their closeness suggests they are the same, & they are not.
