### ISSUE TITLE
Allow direct publishing when creating entries

### ISSUE THREAD

**Issue by LiamMartens** [GraphCMS/Roadmap#25]
Useful when first populating the system

**Comment by paales** [comment]
👍  Have forgotten this about 80% of the time when entering content.

**Comment by mlukaszczyk** [comment]
Its kind of an UX nightmare right now, so we are going to fix this asap ;) 

Note that currently all content entries, even unpublished are served via the API. At this point we are not certain if we should filter them out completely from the API.

**Comment by LiamMartens** [comment]
I know it serves everything but from a user perspective Unpublished records still mean "is not live"

**Comment by d-winter** [comment]
Hey @LiamMartens 
you can now save and publish in one step.
Thanks for reporting!
